---
require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/**/*
    - lib/generators/**/*.rb

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

##########
# LAYOUT #
##########

Layout/LineLength:
  Max: 125
  Exclude:
    - ajax-datatables-rails.gemspec

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

##########
# NAMING #
##########

Naming/FileName:
  Exclude:
    - lib/ajax-datatables-rails.rb
