AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*
    - lib/generators/**/*.rb
    - gemfiles/*
    - spec/**/*

Style/Documentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 130

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/ajax-datatables-rails.rb

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
