---
require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/dummy/**/*

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/BlockDelimiters:
  AllowedPatterns: ['expect']

##########
# LAYOUT #
##########

Layout/LineLength:
  Max: 150
  Exclude:
    - ajax-datatables-rails.gemspec

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

##########
# NAMING #
##########

Naming/FileName:
  Exclude:
    - lib/ajax-datatables-rails.rb

#########
# RSPEC #
#########

RSpec/MultipleExpectations:
  Max: 7

RSpec/NestedGroups:
  Max: 6

RSpec/ExampleLength:
  Max: 9

RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/NotToNot:
  EnforcedStyle: to_not
