---
name: CI Oracle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 4 1 * *'
  # Run workflow manually
  workflow_dispatch:

jobs:
  rspec:
    runs-on: ubuntu-latest

    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.rails }}_with_${{ matrix.adapter }}.gemfile

    services:
      oracle:
        image: 'container-registry.oracle.com/database/free:23.8.0.0-lite'
        ports: ['1521:1521']
        env:
          ORACLE_PWD: oracle

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.4'
          # - '3.3'
          # - '3.2'
          # - '3.1'
          # - 'head'
        rails:
          - rails_8.0
          # - rails_7.2
          # - rails_7.1
        adapter:
          - oracle_enhanced
        # exclude:
        #   # Disabled for now because of build error:
        #   #  /opt/hostedtoolcache/Ruby/3.0.7/x64/lib/ruby/3.0.0/psych.rb:457:in
        #   # `parse_stream': undefined method `parse' for #<Psych::Parser:0x000055b6cc7b6898
        #   # @handler=#<Psych::Handlers::DocumentStream:0x000055b6cc7b69b0 @stack=[],
        #   # @last=nil, @root=nil, @start_line=nil, @start_column=nil, @end_line=nil,
        #   # @end_column=nil, @block=#<Proc:0x000055b6cc7b68e8
        #   # /opt/hostedtoolcache/Ruby/3.0.7/x64/lib/ruby/3.0.0/psych.rb:391>>,
        #   # @external_encoding=0> (NoMethodError)
        #   # from
        #   # /home/runner/work/ajax-datatables-rails/ajax-datatables-rails/vendor/bundle/ruby/3.0.0/gems/ruby-oci8-2.2.14/ext/oci8/apiwrap.rb:64:in
        #   # `create_apiwrap'
        #   - rails: 'rails_7.2'
        #     adapter: 'oracle_enhanced'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
        env:
          DB_ADAPTER: ${{ matrix.adapter }}

      - name: Run RSpec
        env:
          DB_ADAPTER: ${{ matrix.adapter }}
        run: bin/rspec

      - name: Publish code coverage
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/coverage.json
